version: '3.9'

services:
  postgres:
    image: postgres:16.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: youshare
      POSTGRES_USER: youshare
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: # use different port to avoid conflicts with host's postgres
      - 6543:5432

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
